# QA environment overrides — applied to kind-coffee-qa cluster
# CI pipeline updates image.tag here on every successful push to main

namespace: coffee-qa
env: qa

image:
  tag: 1dcc6cc51d780e281d3eeb0d5055aa7997419b49
